apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Deployment","apiVersion":"apps/v1","metadata":{"name":"biz-app","labels":{"app":"biz-app"}},"spec":{"replicas":4,"selector":{"matchLabels":{"app":"biz-app"}},"template":{"metadata":{"labels":{"app":"biz-app"}},"spec":{"containers":[{"name":"nginx","image":"nginx:1.23.1-alpine","resources":{}}]}},"strategy":{}},"status":{}}
  labels:
    app: biz-app
  name: biz-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: biz-app
  strategy: {}
  template:
    metadata:
      labels:
        app: biz-app
    spec:
      containers:
      - image: nginx:7.85.1-alpine
        name: nginx
        resources: {}
status: {}
